services:
  transmission:
    image: 'lscr.io/linuxserver/transmission:latest'
    environment:
      - SERVICE_URL_TRANSMISSION_9091
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - 'USER=${SERVICE_USER_ADMIN}'
      - 'PASS=${SERVICE_PASSWORD_ADMIN}'
    volumes:
      - 'transmission-config:/config'
      - '/mnt/videos/movies:/downloads'
      - 'transmission-watch:/watch'
    healthcheck:
      test:
        - CMD
        - curl
        - '-sSfL'
        - '-u'
        - '${SERVICE_USER_ADMIN}:${SERVICE_PASSWORD_ADMIN}'
        - 'http://localhost:9091/'
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  transmission-config: null
  transmission-watch: null
